# Generated by Django 4.1.1 on 2023-07-18 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_customerorder_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=8)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(max_length=255, null=True)),
                ('line3', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 18, 20, 26, 41, 500354)),
        ),
    ]
