# Generated by Django 4.1.1 on 2023-07-18 19:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0009_alter_customerorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storeapp.deliveryaddress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 18, 20, 38, 26, 235000)),
        ),
    ]
