# Generated by Django 4.1.1 on 2023-07-20 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_alter_cartitem_cost_alter_customerorder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='delivery',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=100),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='fname',
            field=models.CharField(default='Firstname', max_length=255),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='line1',
            field=models.CharField(default='Line 1', max_length=255),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='line2',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='line3',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='lname',
            field=models.CharField(default='Lastname', max_length=255),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='postcode',
            field=models.CharField(default='Postcode', max_length=8),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 20, 19, 33, 40, 187598)),
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
