# Generated by Django 4.1.1 on 2023-07-20 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0015_alter_customerorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 20, 20, 53, 1, 274170)),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='delivery_instructions',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
